### PR TITLE
GHC 7.6 Support

### PR DESCRIPTION
**Pull request by alevy**
lifted-base no longer contains addMVarFinalizer

### CODE REVIEW

**Comment by deian** [comment]
+1

**Comment by markwright** [comment]
true but it needs:

1) dep on >= lifted-base-0.2

2) #if MIN_VERSION_base(4,6,0) around these diffs so it will still work with ghc 7.4.2 like:

https://github.com/gentoo-haskell/gentoo-haskell/blob/master/dev-haskell/mongodb/files/mongodb-1.3.0-ghc-7.6.patch

anyway I note the mongoDB 1.3.0 build is broken with ghc 7.6.1 and lifted-base 0.2

**Comment by alevy** [comment]
@markwright thanks for the tip on this. I've tested it with both 7.6 and 7.4 now following your example.

**Comment by knsd** [comment]
Thanks for your pull request!

I will update version on hackage tomorrow.

**Pull request merged**
