### PR TITLE
Convert to use hashtables, as Data.HashTable went away.

### PR DESCRIPTION
**Pull request by ezyang**
Fixes Issue #16

Signed-off-by: Edward Z. Yang ezyang@mit.edu

### CODE REVIEW

**Comment by gregwebs** [comment]
Does any of this need to be conditional on GHC or base version?

**Comment by gregwebs** [comment]
@ezyang do you know how this effects backwards compatibility?

**Comment by ezyang** [comment]
Hmm, that's a good question. In some respects, this should have no change on BC, because all you're doing is swapping out an internal implementation with another one (adding an extra Cabal dependency in the process); no interface changes. So as long as hashtables is supported in all the versions you care about (someone needs to check), it should be fine. But some people might prefer to have a version which doesn't have the extra hashtables dependency, in which case a lot of conditionalizing might be necessary. (Sorry about missing the earlier inquiry)

**Comment by knsd** [comment]
Thanks, Edward! It's already on Hackage.

**Pull request merged**
